### ISSUE TITLE
floating parameter

### ISSUE THREAD

**Issue by aendler** [completementgaga/calc_hack#1]
How could I use a range of decimal values ​​for the parameters?

**Comment by completementgaga** [comment]
Did you try to enter a list of values like below?
a: 6.3,6.4,6.5,6.6,6.7,6.8

Maybe the key point is to separate values with commas and to use the dot for the decimal separator.

Best,
Gaël.

**Comment by aendler** [comment]
Dear   Gaël,  your   recipe    works!  thanks,  
I was
trying to change your code using NumPy's
 arange, but it didn't work.
I am a professor of physics at UFRGS (Brazil) and my quiz questions, most of the time, involve non-integer values.

I  have  other  issues/questions , but I think it is better to open another topic to keep the organization 
Best,
antonio

**Comment by completementgaga** [comment]
Dear Antonio,
For simplicity, I chose not to add too many options for the definition of the sets in which the values of the wildcards are sampled.
The treatment of the range command for integer intervals is done in the if statement starting at line 32 of the python script. the condition vals[0]=='r' is interpreted as vals starting with 'range', afterwards the string is evaluated as python code: L=eval(vals).
You could add extra conditional statements to allow other set descriptions using python code. If you manage something in this direction, please consider doing a pull request.

A maybe simpler option is to keep with the current script, to use only integer parameters and divide them by a suitable power of 10 in your formulae.
Best,
Gaël.

**Comment by completementgaga** [comment]
I enabled the use of numpy and of any iterable to define the set of values in which the parameters are sampled.
@aendler: you can now use 
a: numpy.arange(2.2,9.3,0.1)
provided numpy is installed on your system and you use the flag -n when calling calc_hack.py
(more details in the updated readme)
