### ISSUE TITLE
wildcard variable    names 

### ISSUE THREAD

**Issue by aendler** [completementgaga/calc_hack#2]
Hi Gaël, 

I think the name of the variables has a limitation in your script because when I use your example:
%%%%%%%%%%%%%%%%%%%%%%%%%%
\begin{quiz}{An example of a quiz with calc}
\begin{numerical}[points=2]{Basic addition, calculated}
  What is ${a}+{b}$?
   
  \item {a}+{b} 
  \end{numerical}
  params\\
  a: range(19)\\
  b: -7,1,2,3,4,5,6,7,8,9,10,11,14,15,17,18,19,20,21,22,23,24,27,28,29,-8\\
  digits(for the result)\\
  1
%%%%%%%%%%%%%%%%%%%%%%%%%%
I can generate the xml calculated successfully, but when I change the name of the variables as below
%%%%%%%%%%%%%%%%%%%%%%%%%%
\begin{quiz}{An example of a quiz with calc}
\begin{numerical}[points=2]{Basic addition, calculated}
  What is ${a1}+{a2}$?
   
  \item {a1}+{a2} 
  \end{numerical}
  params\\
  a1: range(19)\\
  a2: -7,1,2,3,4,5,6,7,8,9,10,11,14,15,17,18,19,20,21,22,23,24,27,28,29,-8\\
  digits(for the result)\\
  1
%%%%%%%%%%%%%%%%%%%%%%%%%%%%

your script returns the following error:

 python3 calc_hack.py 'calcquiz2.tex'
Traceback (most recent call last):
  File "calc_hack.py", line 169, in <module>
    u=findcalculated(texfile)
  File "calc_hack.py", line 38, in findcalculated
    calculated.append([count,[var,set(eval('['+ vals+']'))]])
  File "<string>", line 1
    [:range(19)]
     ^
SyntaxError: invalid syntax

%%%%%%%%

best, 
antonio

**Comment by completementgaga** [comment]
This could be fixed easily, but are you sure moodle can handle wildcards with more than one character?
The fix would be to alter lines 30 and 31 of the python script.
Best,
G.

**Comment by aendler** [comment]
Yes, I tried it directly on moodle and it works.
I don't know much about phyton, so what exactly is the change you should make on lines 30 and 31:

%%%%%%%%%%%%%%%%%%%
 30      var=line[0]
 31      vals=line[2:].rstrip('\\').rstrip(',')
%%%%%%%%%%%%%%%%%%%

 thank you for your attention and congratulations  on this project of yours!! it is helping me a lot in my work in these times of distance learning.

best
a.e.

**Comment by completementgaga** [comment]
I think this is solved. Please, open a new issue if it is not the case.
