### ISSUE TITLE
calc hack inside cloze environment

### ISSUE THREAD

**Issue by pmunhoz** [completementgaga/calc_hack#4]
Dear Gaël,

 I am very interested in your script calc_hack for latex moodle package! Thank you very much for this script!

I wonder if is it possible to have this script running when using cloze environment (latex moodle, version 0.8). Below, I have changed  the calcquiz.tex to what I think it should be implemented with cloze environment, but the script fails to produce a trusted .xml to import to Moodle.

Thanks for your help,
Pablo.

\documentclass[12pt]{article}
\usepackage{moodlept}%or moodle.sty v0.8
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}

\begin{document}

\begin{quiz}{An example of a quiz with calculated questions}
\begin{cloze}{Basic addition, calculated}
\begin{numerical}[points=2]
  What is ${a}+{b}$?
  \item {a}+{b}
  \end{numerical}
  params\\
  a: range(19)\\
  b: -7,1,2,3,4,5,6,7,8,9,10,11,14,15,17,18,19,20,21,22,23,24,27,28,29,-8\\
  digits(for the result)\\
  1
\end{cloze}

\begin{cloze}{estudo de uma sequência}
  \begin{multi}
  Seja, para todo inteiro $n>0$, \[v_n=\frac{e^n}{n}.\]
  A sequência $(v_n)$ possui o limite
  \item $1$.
  \item $0$.
  \item $e$.
  \item* $+\infty$.
  \end{multi}
\end{cloze}

\begin{cloze}{Sequências, Convergência}
\begin{multi}[multiple]
A sequência $\displaystyle \frac{n^2}{{b}} \text{sen}\left(\frac{{a}}{n^{2}}\right)$
\item* Converge a {a}/{b}
\item diverge, pois fica oscilando com valores positivos e negativos.
\item tem limite igual a infinito
\item Converge a 0.
\end{multi}
params\\
a: range(1,9)\\
b: 1,2,3\\
digits(for the calculated results)\\
0
\end{cloze}
\end{quiz}
\end{document}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

**Comment by completementgaga** [comment]
Hello and thanks you for you request. If I understand well there is no calculated version of cloze questions. Maybe something called "stack question type" could help you:  https://moodle.org/mod/forum/discuss.php?d=270994

Otherwise, something that gives you total freedom on the resulting quiz is to produce massively  variants of a given numerical, cloze or multichoice question using a programming language that handles well math computations. I did this successfully with [sagemath](https://www.sagemath.org/). A colleague of mine used python with the [SymPy library](https://www.sympy.org/en/index.html) for the same purpose. Both approaches are still based on the moodle package for latex: we programmatically produce the .tex source file for the quiz. A key feature here is that both SageMath and SymPy export math expressions in the latex format, thanks to the latex command.

**Comment by pmunhoz** [comment]
Dear Gaël,

Thanks for your prompt response and advices. 

You're right, I am willing to use moodle package (version 0.8) with cloze numerical questions, where I am able to have subquestions (as a kind of railway for students to follow the lines of reasoning to solve the total of a question, perhaps scoring points in some subquestions). 

I would also like to avoid to handle with a number of versions of the same question (this is indeed well implemented with the sagemath, SymPy, as you mentioned, or LuaLaTeX with directlua, or even sagetex, pythontex, among others), perhaps using calculated questions, somehow, within cloze questions. Currently, you're also correct, it seems there is no native support for that in Moodle interface, aside the stack question you have also pointed out, but there comes the other problem: the learning curve x time. 

Prior to start this answer I have found a somewhat related query of a Moodle user in the forum link below, where the first answer details a script, as far as I could understand, that inserts the calculated question skills into a cloze question! The script seems to use a web-based interface to upload a .xml (previously adapted with the syntax of curly braces) file with cloze questions to receive the random values specified during the procedure and you finally ends with a .clz (scripted .xml) file to import back to Moodle as a calculated questions with subquestions.

 https://moodle.org/mod/forum/discuss.php?d=132225

As for now, I am wondering if it would be possible to merge your script and this web-based script in a way to have an entirely automated script performing exactly what I am looking for since the very beginning of this issue.

Thanks a lot for your time,

**Comment by pmunhoz** [comment]
Oops, I forgot the link: https://moodle.org/mod/forum/discuss.php?d=132225

**Comment by completementgaga** [comment]
About Steve Turley's proposal https://moodle.org/mod/forum/discuss.php?d=132225
For various reasons, I think it would be better to avoid interactions with an online script (currently, the alleged address yields a 404 error). The idea could be taken from there to be redone in python, within our script. However, I am not willing to do this fro the moment. Feel free to do it and to submit a pull request.

Best,
Gaël.

**Comment by pmunhoz** [comment]
Dear Gaël,

Thank you very much for your reply. Indeed the Turley's script seems to be missing! No worry, I will find another way to implement my query! Perhaps STACK questions do the job!

Best regards,
Pablo.
